theme = "solarized-dark"
icons = "awesome"

#[[block]]
#block = "custom"
#command = "trainspeed"
#interval = 5

[[block]]
block = "battery"
driver = "upower"
device = "battery_BAT0"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 10.0

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"

[[block]]
block = "net"
device = "wlp3s0"
signal_strength = true
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "temperature"
format = "{max}°C"
collapsed = false

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "sound"
step_width = 2

[[block]]
block = "time"
interval = 60
format = "%Y-%m-%d %H:%M"
